# Substitution and Permutation Network

## Design Choices

The following are some design choices for the implemented SPNetwork:
1. There are 4 layers to this SPN.
2. For every layer, identical Substitution boxes are being used.
3. For every layer, idential Permutation box is being used.
4. This SPN takes in 16-bit input and produces 16-bit output
5. Refer to ???.pdf for a detailed diagram of the SPN

#### The following will demonstrate the implementation of our SPN Network.

## 1 Import necessary files

Implementation of Substitution Boxes, Permutation Boxes and the overall SPNetwork can be found in class.py.  
Other necessary functions will be found in utils.py.

In [1]:
from classes import *
from utils import *

## 2 Encryption

### 2.1 Create a SPN Object

An SPN object 'spn' will be created for the encryption.

In [2]:
spn = SPN()

### 2.2 Initialise Key
For this demonstration, we will be using the master key of 42069 which is 1010 0100 0101 0101 in binary.

In [20]:
key = 42069
print("Key:                 ", key)
print("Key(binary):         ", format(key, f'0{16}b'))

Key:                  42069
Key(binary):          1010010001010101


### 2.3 Encrypt plaintext

The plaintext that is encrypted will be 2911 which is 0000 1011 0101 1111 in binary.  
The encryption method will take in 2 arguments - plaintext and key.

In [14]:
plaintext = 2911
print("Plaintext:           ", plaintext)
print("Plaintext(binary):   ", format(plaintext, f'0{16}b'))

ciphertext = spn.encrypt(plaintext, key)

Plaintext:            2911
Plaintext(binary):    0000101101011111


The resulting ciphertext will be 11572 which is 0010 1101 0011 0100 in binary can be shown below.

In [16]:
print("Ciphertext:           ", ciphertext)
print("Ciphertext(binary):   ", format(ciphertext, f'0{16}b'))

Ciphertext:            11572
Ciphertext(binary):    0010110100110100


## 3 Decryption

### 3.1 Decrypt ciphertext

The SPN object 'spn' and the key (42069) will be reused for the decryption.

In [23]:
decryption_result = spn.decrypt(ciphertext, key)

print("Decryption Result:           ", decryption_result)
print("Decryption Result(binary):   ", format(decryption_result, f'0{16}b'))

Decryption Result:            2911
Decryption Result(binary):    0000101101011111


As we can see from above, the result from the decryption is the initial plaintext of 2911.